### ISSUE TITLE
sign in form remove 00 and +

### ISSUE THREAD

**Issue by amiresfahani** [fizzl/OneCallCaspian#19]
the sign in id field should remove + and 00 from phone number and have an example number in background 443303500153 also sign up form needs an example number in background

**Comment by fizzl** [comment]
Build OneCallCaspian-2015-04-27-03 prevents use from entering 0 or + at the start. It will also require the user to begin his username with the selected country code.

**Comment by amiresfahani** [comment]
best if we remove 00 or + from number and try login with same number without 00 or +

**Comment by fizzl** [comment]
This problem was solved as a side effect of the new login, signup and forgot password systems.
